# Generated by Django 3.1.2 on 2020-10-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='foobar', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='foobar', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='foobar', max_length=10),
        ),
    ]
