# Generated by Django 3.1.2 on 2020-10-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201030_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='No address provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='No mobile provided', max_length=10),
        ),
    ]
